### ISSUE TITLE
PIP automatic installation not working

### ISSUE THREAD

**Issue by Briantoma** [AssoDIT/DaVinici-Resolve-Stills-Markers#2]
Pillow not found. Installing...
Traceback (most recent call last):
  File "/Library/Application Support/Blackmagic Design/DaVinci Resolve/Workflow Integration Plugins/Stills_Markers_python_V9.py", line 77, in <module>
    from PIL import Image, ImageDraw, ImageFont
ModuleNotFoundError: No module named 'PIL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Application Support/Blackmagic Design/DaVinci Resolve/Workflow Integration Plugins/Stills_Markers_python_V9.py", line 81, in <module>
    pip.main(['install', 'Pillow'])
AttributeError: module 'pip' has no attribute 'main'

**Comment by bryanrandell** [comment]
I will add an installer bash script for Macos to check the python installation on the system, then install the needed external libraries and finally move the main script to the DaVinci Resolve Workflow Integration Plugin path

**Comment by bryanrandell** [comment]
For the moment I have change the way it tries to install Pillow with a subprocess check call
