### ISSUE TITLE
Script doesn't find timeline

### ISSUE THREAD

**Issue by Briantoma** [AssoDIT/DaVinici-Resolve-Stills-Markers#4]
Pillow is already installed.
loaded settings from /Applications/DaVinci Resolve/DaVinci Resolve.app/Contents/Libraries/Fusion/settings.json
{'markers': 'Any', 'export': True, 'export_to': '', 'format': 'jpg', 'resize_stills': False, 'resize_percentage': 50, 'replace_original_exports': True, 'rename_with_meta': 'clip_name', 'restrict_to_in_out': True, 'remove_drx': True, 'create_export_folder_timeline_name': True, 'create_sub_folder': True, 'sub_folder_name': 'Stills', 'compress': False}
didn't find timeline 01_20240213 in project
didn't find timeline 01_20240213 in project
markin  - markout 
Traceback (most recent call last):
  File "/Library/Application Support/Blackmagic Design/DaVinci Resolve/Workflow Integration Plugins/Stills_Markers_python_V9.py", line 1113, in <module>
    markIn_frame = frame_from_timecode(markIn, frame_rate, drop_frame)
  File "/Library/Application Support/Blackmagic Design/DaVinci Resolve/Workflow Integration Plugins/Stills_Markers_python_V9.py", line 291, in frame_from_timecode
    return smpte.getframes(timecode)
  File "/Library/Application Support/Blackmagic Design/DaVinci Resolve/Workflow Integration Plugins/Stills_Markers_python_V9.py", line 102, in getframes
    if int(tc[9:]) > self.fps:
ValueError: invalid literal for int() with base 10: ''

The script doesn't find the timeline if it is in a sub subfolder:
<img width="425" alt="Capture d’écran 2024-02-13 à 16 36 41" src="https://github.com/AssoDIT/DaVinici-Resolve-Stills-Markers/assets/45849896/e215188b-3c9c-413b-88b8-d86e97053d30">

Any higher location works.

**Comment by bryanrandell** [comment]
New commit.
The script will now find timeline even under multiples sub folder
