### ISSUE TITLE
Problem with 23.98fps timeline?

### ISSUE THREAD

**Issue by Briantoma** [AssoDIT/DaVinici-Resolve-Stills-Markers#5]
error message:
Pillow is already installed.
loaded settings from /Applications/DaVinci Resolve/DaVinci Resolve.app/Contents/Libraries/Fusion/settings.json
Traceback (most recent call last):
  File "/Library/Application Support/Blackmagic Design/DaVinci Resolve/Workflow Integration Plugins/Stills_Markers_python_V10.py", line 1138, in <module>
    markIn_frame = frame_from_timecode(markIn, frame_rate, drop_frame)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Blackmagic Design/DaVinci Resolve/Workflow Integration Plugins/Stills_Markers_python_V10.py", line 291, in frame_from_timecode
    return smpte.getframes(timecode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/Blackmagic Design/DaVinci Resolve/Workflow Integration Plugins/Stills_Markers_python_V10.py", line 102, in getframes
    if int(tc[9:]) > self.fps:
       ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by bryanrandell** [comment]
Don't think so, could be the same "not finding timeline issue"
is the timeline in a sub directory ? And if so, does it not crash when timeline moved to root/master bin ?

**Comment by Briantoma** [comment]
It's the opposite bug now! 
It doesn't find the timeline if it's at root but finds it if it's in a subfolder 😅

**Comment by bryanrandell** [comment]
My bad
I'll fix this asap

**Comment by bryanrandell** [comment]
should be ok in this new version
